name: Will Townsend
markdown: redcarpet
highlighter: pygments
permalink: /:year/:title

description: I like to make iOS apps and play guitar.
url: https://will.townsend.io

navigation:
  - title: Blog
    url: /blog/
  - title: About
    url: /about/
  - title: AppStore
    url: https://itunes.apple.com/nz/artist/will-townsend/id482491153
